In [19]:
import numpy as np

In [20]:
a = np.array([1, 2, 3])
print(a)
b = np.array([[9, 9, 3, 1], [8, 1, 3, 6]])
print(b)

[1 2 3]
[[9 9 3 1]
 [8 1 3 6]]


In [21]:
# get dimension
a.ndim

1

In [22]:

# get shape
b.shape

(2, 4)

In [23]:
a.dtype

dtype('int32')

In [24]:
print(a.itemsize)
print(a.size)

4
3
