In [ ]:
import numpy as np

#### MATHEMATICS

In [ ]:
a = np.array([1, 2, 3, 4])
print(a)

In [ ]:
# this will add 2 to all the element of the array
a += 2 
a

In [ ]:
a -= 2
a

In [ ]:
b = np.array([1, 0, 1, 0])
a + b

In [ ]:
a ** 2

In [ ]:
np.sin(a)

#### Linear Algebra

In [ ]:
a = np.ones((2, 3), dtype='int32')
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a,b)

In [62]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statics

In [65]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.min(stats)

1

In [70]:
np.max(stats, axis = 1)

array([3, 6])

In [71]:
np.sum(stats, axis = 0)

array([5, 7, 9])