##### Reorganizing Arrays

In [13]:
import numpy as np

before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((2, 4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [14]:
# vertical stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

##### Miscellaneous

In [15]:
# load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [16]:
# boolean masking and advanced indexing
filedata < 30

array([[ True,  True,  True,  True, False, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True, False, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [22]:
filedata[filedata < 0]

array([], dtype=int32)

In [23]:
# you can index with a list in NumPY
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 6, 0]]

array([2, 7, 1])

In [26]:
np.all(filedata > 50 , axis= 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [30]:
filedata[(filedata > 50) & (filedata < 100)]

array([75, 75, 55, 78, 76, 88])